source 'https://rubygems.org'
gem 'htmlbeautifier', '~>1.1.1'
gem 'activesupport', '~>4.2.4'
gem 'activerecord', '~>4.2.4'
gem 'net-ping', '~>1.7.8'
gem 'sinatra', '~>1.4.6'
gem 'minitest', '5.8.2'
gem 'ping', '~>0.0.8'
gem 'nokogiri'
gem 'sqlite3'
gem 'puma'
gem 'net'
